name: flutter_cluster_dashboard
description: Instrument Cluster demo app using Flutter for AGL

publish_to: 'none'
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

# packages used
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.19.0
  http: ^1.2.2
  yaml: ^3.1.2

  grpc: ^4.0.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cert/
    - images/
